CREATE TABLE bags (

    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    title VARCHAR(256) NOT NULL,

    CONSTRAINT pk_bag_id PRIMARY KEY(id)
);

CREATE TABLE items (

    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1),
    bag_id INTEGER NOT NULL,
    title VARCHAR(256) NOT NULL,

    CONSTRAINT pk_item_id PRIMARY KEY(id),
    CONSTRAINT fk_item_bag_id FOREIGN KEY(bag_id) REFERENCES bags(id)
);
