CREATE TABLE bags (

    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),

    title VARCHAR(256),

    CONSTRAINT primary_key PRIMARY KEY (id)
);

INSERT INTO bags(title) VALUES ('BAG 1');

INSERT INTO bags(title) VALUES ('BAG 2');
